// Czech copy. Texts follow bruxx.cz; structure is shared with en.js and de.js
// (a test keeps the three in step).
export default {
  meta: {
    site: 'Bruxx',
    tagline: 'belgická brasserie v Praze',
    description:
      'Belgická brasserie na náměstí Míru: čerstvé mušle třikrát týdně, hranolky smažené v hovězím loji, přes 60 belgických piv a lutyšské vafle.',
  },

  nav: {
    skip: 'Přeskočit na obsah',
    home: 'Úvod',
    menu: 'Menu',
    beer: 'Piva',
    about: 'O nás',
    gallery: 'Galerie',
    kids: 'Pro děti',
    recipes: 'Recepty',
    contact: 'Kontakt',
    reserve: 'Rezervace',
    reserveTable: 'Rezervovat stůl',
    call: 'Zavolat',
    open: 'Otevřít menu',
    close: 'Zavřít menu',
    language: 'Jazyk',
    themeLight: 'Světlý vzhled',
    themeDark: 'Tmavý vzhled',
    main: 'Hlavní navigace',
  },

  status: {
    openUntil: 'Otevřeno do {t}',
    opensToday: 'Otevíráme dnes v {t}',
    opensOn: 'Otevíráme {d} v {t}',
    tomorrow: 'zítra',
  },

  days: ['neděle', 'pondělí', 'úterý', 'středa', 'čtvrtek', 'pátek', 'sobota'],
  daysShort: ['ne', 'po', 'út', 'st', 'čt', 'pá', 'so'],
  daysRange: { '1': 'pondělí', '2,3': 'úterý – středa', '4,5,6': 'čtvrtek – sobota', '0': 'neděle' },

  home: {
    hero: {
      eyebrow: 'Náměstí Míru · Praha 2',
      title: ['belgická', 'brasserie', 'v praze'],
      lead: 'Čerstvé mušle, křupavé hranolky, perfektně vychlazená piva a legendární vafle. Čtyři základní kameny, na kterých stojí Bruxx.',
      menu: 'Prohlédnout menu',
      scroll: 'Dolů',
    },
    marquee: ['moules', 'frites', 'bière', 'gaufres', 'huîtres', 'escargots', 'crevettes'],
    pillars: {
      eyebrow: 'Bruxx exclusive',
      title: 'čtyři základní kameny',
      items: [
        {
          key: 'mussels',
          title: 'čerstvé mušle',
          kicker: '3× týdně z Yerseke',
          text: 'Holandské mušle dovážíme třikrát týdně z oblasti Eastern Scheldt. Nejvíc chutnají na bílém víně, šéfkuchař má nejraději slávky Tin Tin.',
          photo: 'dish-mussels',
        },
        {
          key: 'fries',
          title: 'hranolky',
          kicker: 'dvakrát smažené v hovězím loji',
          text: 'Vše začíná výběrem správné odrůdy brambor a končí typicky belgickým dvojitým smažením. Podáváme s domácí majonézou z olivového oleje.',
        },
        {
          key: 'beer',
          title: 'pivo',
          kicker: '60+ lahvových · 8 na čepu',
          text: 'Od witbieru, lambiku a geuze až po trapistická piva. Našim nejprodávanějším lahvovým pivem je ambrové Kwak.',
          photo: 'beer-pour',
        },
        {
          key: 'waffles',
          title: 'lutyšské vafle',
          kicker: 'z kynutého těsta',
          text: 'Existují zákusky, na kterých může vzniknout závislost. Trvalo několik týdnů, než jsme jejich křupavost i chuť dovedli k dokonalosti.',
          photo: 'dish-waffle',
        },
      ],
      more: 'Celý příběh',
    },
    lunch: {
      eyebrow: 'Polední menu',
      title: 'dnes v poledne',
      hours: 'Po–Pá · 11:00–15:00 nebo do vyprodání',
      weekend: 'V sobotu, v neděli a ve státní svátky denní nabídku nepřipravujeme. Vyberte si, prosíme, ze stálého menu.',
      empty: 'Polední nabídka se právě připravuje.',
      full: 'Celé menu',
    },
    stats: [
      { value: 60, suffix: '+', label: 'druhů belgických lahvových piv' },
      { value: 8, suffix: '', label: 'svrchně kvašených piv na čepu' },
      { value: 3, suffix: '×', label: 'týdně čerstvé mušle a ryby' },
      { value: 45, suffix: '', label: 'míst na galerii pro uzavřené společnosti' },
    ],
    dishes: {
      eyebrow: 'Z naší kuchyně',
      title: 'talíře, které stojí za cestu',
      hint: 'Táhněte do strany',
    },
    beer: {
      eyebrow: 'Pivní sommeliér',
      quote: 'V Bruxxu se od začátku specializujeme na ta nejlepší piva z Belgie.',
      author: 'Robert Vaverka',
      role: 'generální manažer a spolumajitel',
      cta: 'Nechte si doporučit pivo',
    },
    private: {
      eyebrow: 'Soukromé akce',
      title: 'galerie jen pro vás',
      text: 'Galerie restaurace pojme až 45 hostů a dá se vyhradit pro uzavřenou společnost — narozeniny, firemní večeře nebo degustaci belgických piv.',
      cta: 'Domluvit akci',
    },
    events: {
      eyebrow: 'Akce & sezóna',
      title: 'během roku vaříme slavnosti',
      lead: 'Sezónní akce a speciality našich šéfkuchařů servírujeme po celý den. Sledujte nás — nejbližší gurmánský zážitek se právě připravuje.',
      items: [
        { title: 'Krevetový festival', photo: 'dish-prawns' },
        { title: 'Humří hody', photo: 'dish-scallops' },
        { title: 'Vánoční šneci', photo: 'dish-escargots' },
      ],
    },
    teasers: {
      kids: { eyebrow: 'Pro děti', title: 'dětský koutek a víkendový brunch', cta: 'Pro rodiny' },
      recipes: { eyebrow: 'Recepty', title: 'cibulačka Bruxx doma', cta: 'Recepty šéfkuchaře' },
    },
    visit: {
      eyebrow: 'Kde nás najdete',
      title: 'náměstí míru 9',
      route: 'Naplánovat trasu',
      hours: 'Otevírací doba',
    },
  },

  menu: {
    eyebrow: 'Jídelní a nápojový lístek',
    title: 'menu',
    lead: 'Belgické receptury, mušle třikrát týdně čerstvé a ke každému jídlu domácí bageta zdarma.',
    tabs: { lunch: 'Polední menu', food: 'Jídla', drinks: 'Nápoje', wine: 'Vína', beer: 'Piva' },
    search: 'Hledat v menu',
    searchPlaceholder: 'Mušle, Kwak, vafle…',
    allergens: 'Alergeny',
    exclude: 'Skrýt jídla s alergenem',
    clear: 'Zrušit filtr',
    none: 'Nic jsme nenašli. Zkuste jiné slovo nebo zrušte filtr.',
    live: 'Aktuální nabídka přímo z kuchyně',
    snapshot: 'Nabídka ke dni {d}',
    currency: 'Kč',
    jump: 'Kategorie',
    allergensTitle: 'Seznam alergenů',
    allergensNote: 'Čísla u jídel označují alergeny. Rádi vám poradíme, na co se zeptat obsluhy.',
    lunchTitle: 'Polední menu',
    lunchHours: 'Pondělí–pátek, 11:00–15:00 nebo do vyprodání',
    new: 'novinka',
    items: '{n} položek',
    langNote: '',
  },

  allergens: {
    1: 'obiloviny s lepkem',
    2: 'korýši',
    3: 'vejce',
    4: 'ryby',
    5: 'arašídy',
    6: 'sója',
    7: 'mléko',
    8: 'skořápkové plody',
    9: 'celer',
    10: 'hořčice',
    11: 'sezam',
    12: 'oxid siřičitý a siřičitany',
    13: 'vlčí bob',
    14: 'měkkýši',
  },

  subscribe: {
    title: 'Polední menu do e-mailu',
    text: 'Každý všední den ráno vám pošleme, co se dnes vaří.',
    label: 'Váš e-mail',
    placeholder: 'jmeno@email.cz',
    submit: 'Přihlásit',
    consent: 'Souhlasím se zpracováním osobních údajů',
    sent: 'Hotovo — e-mail jsme předali k přihlášení odběru.',
    added: 'E-mail byl úspěšně přidán.',
    removed: 'E-mail byl úspěšně odhlášen.',
    invalid: 'E-mail je ve špatném formátu.',
    unavailable: 'Přihlášení teď nejde odeslat. Zkuste to prosím za chvíli.',
  },

  beer: {
    eyebrow: 'Belgická piva',
    title: 'piva',
    lead: 'V Bruxxu se od začátku specializujeme na ta nejlepší piva z Belgie. Nechte si je doporučit přímo od generálního manažera Roberta Vaverky.',
    intro: {
      name: 'Robert Vaverka',
      role: 'generální manažer, spolumajitel a pivní sommeliér',
      text: 'Světem belgických piv od witbieru, lambiku a geuze až po trapistická piva vás provedou naši pivní someliéři. Na čepu máme osm svrchně kvašených piv a každých čtrnáct dní jedno nové pivo z tuzemského minipivovaru.',
    },
    sections: [
      {
        title: 'Ovocná piva',
        photo: 'beer-st-bernardus',
        paragraphs: [
          'Moje nejoblíbenější ovocné pivo je Kasteel Rouge, které se vyrábí z tmavého piva Kasteel Donker. Toto pivo více než 6 měsíců dozrává a kvasí na višních a se svými 8 % alkoholu patří mezi nejsilnější ovocná piva Belgie.',
          'Pivovar Van Honsebrouck, kde toto úžasné pivo vyrábějí, jsem před pár lety navštívil a nad pár dobrými pivy poseděl přímo s majitelem Xavierem Van Honsebrouckem. Jeho rodina vlastní zámek, který je vyobrazený i na noze skleničky.',
          'U nás ho rádi nabízíme v kombinaci se zvěřinou, jídly s těžšími omáčkami a s dezerty s lesními plody. Dalším ovocným pivem, které doporučuji, je Liefmans Fruitesse on the Rocks — servíruje se do sklenice plné ledu a je skvělé i jako aperitiv.',
        ],
      },
      {
        title: 'Polotmavá piva',
        photo: 'beer-pour',
        paragraphs: [
          'Kwak z pivovaru Bosteels se servíruje do speciální sklenice ve tvaru velké baňaté zkumavky a při nalévání dochází k lavinovému efektu. Toto polotmavé pivo patří se svými 8,4 % alkoholu k pivním silákům.',
          'Nejlépe si ho vychutnáte s pomalu dušeným hovězím brisketem à la mode s kořenovou zeleninou, bylinkami a petrželovými bramborami.',
        ],
      },
      {
        title: 'Světlá piva',
        photo: 'beer-orval',
        paragraphs: [
          'K pivním silákům s 8,3 % alkoholu patří i Hopus z dílny Brasserie Lefebvre. Doporučíme ho k vegetariánským raviolám s pekanovými ořechy a mascarpone — a ohromíme vás způsobem servírování: usazeninu z lahve dostanete zvlášť v malém panáku a hořkost si regulujete sami.',
          'Mým nejoblíbenějším světlým pivem je Brugge Tripel z pivovaru De Gouden Boom. Má jasně zlatavou barvu a příjemnou hořkost s citrusovými tóny na konci. Já bych k němu vybral grilované kalamáry, krevety a mušle se šafránovým fumetem.',
        ],
      },
      {
        title: 'IPA',
        paragraphs: [
          'Své zástupce u nás má i IPA — více chmelený druh piva s vyšším obsahem alkoholu. V dobách, kdy byla Indie britskou kolonií, se do piva přidávalo víc chmele a alkoholu, aby vydrželo dlouhou cestu.',
        ],
      },
      {
        title: 'Lambická piva',
        photo: 'beer-mort-subite',
        paragraphs: [
          'Nemohu nezmínit Boon Geuze se 7 % alkoholu. Je to lambické pivo ze spontánního kvašení, geuze znamená směs starých a mladých lambiků. Když jsem ho poprvé ochutnal v Antverpách, myslel jsem si, že je zkažené — dnes patří k mým nejoblíbenějším stylům a doporučuji ho hlavně k ústřicím.',
        ],
      },
      {
        title: 'Pivo pro dámy',
        paragraphs: [
          'Pro dámy doporučuji Mongozo Coconut z pivovaru Huyghe s 3,6 % alkoholu. Podává se v kokosové skořápce a chutná jako pivní piña colada. Perfektní k lehkému dezertu, třeba k našemu pistáciovému crème brûlée.',
        ],
      },
    ],
    explorer: {
      eyebrow: 'Pivní lístek',
      title: 'najděte své pivo',
      lead: 'Celý aktuální pivní lístek. Filtrujte podle stylu a síly.',
      all: 'Vše',
      strength: 'Síla',
      strengths: { all: 'Jakákoli', light: 'do 5 %', mid: '5–8 %', strong: 'nad 8 %' },
      sort: 'Řadit',
      sorts: { menu: 'Jako v lístku', abv: 'Podle síly', price: 'Podle ceny' },
      count: '{n} piv',
      none: 'Takové pivo teď na lístku nemáme.',
    },
  },

  about: {
    eyebrow: 'O nás',
    title: 'brasserie z belgických receptur',
    lead: 'Čerstvé mušle, křupavé hranolky, perfektně vychlazená piva a legendární vafle. To jsou čtyři základní kameny, na kterých jsme v centru Prahy vystavěli belgickou brasserii Bruxx.',
    story: [
      'Pod vedením šéfkuchaře Oldy Matouška a spolumajitelů Jana Pípala a Roberta Vaverky připravujeme menu podle originálních belgických receptur a třikrát týdně do Prahy přivážíme čerstvé farmované mušle.',
      'Podobně jako Belgičané si také my potrpíme na hranolky, které si sami připravujeme. V menu nechybějí ani lutyšské recepty, čerstvé ryby, ústřice, šneci a další originální suroviny. A najdete u nás i belgické pralinky.',
      'Od pondělí do pátku servírujeme polední nabídku, která platí vždy od 11 do 15 hodin nebo do vyprodání. Od 11:30 je k dispozici dětský koutek, o víkendech s dozorem.',
    ],
    exclusive: {
      eyebrow: 'Bruxx exclusive',
      title: 'na čem si dáváme záležet',
      items: [
        {
          title: 'čerstvé mušle',
          photo: 'dish-mussels',
          text: 'Holandské mušle dovážíme do Prahy třikrát týdně z oblasti Eastern Scheldt poblíž městečka Yerseke. Kromě originálních receptů je pro nás důležité, aby byly mušle na vašem stole vždy čerstvé a ve výborné kvalitě. Hostům nejvíce chutnají mušle na bílém víně, šéfkuchař Olda Matoušek má nejraději slávky Tin Tin.',
        },
        {
          title: 'hranolky',
          text: 'Málokdo si umí představit, kolik práce se skrývá za křupavými a dozlatova smaženými hranolky. Vše začíná složitým výběrem vhodné odrůdy a správného typu brambor a končí pro belgickou kuchyni typickým dvojitým smažením v hovězím loji.',
        },
        {
          title: 'ryby',
          photo: 'dish-tuna',
          text: 'Stejně jako mušle dovážíme třikrát týdně i čerstvé ryby. Na váš stůl putují ze Středozemního moře, ze západního i severního pobřeží Evropy nebo z Indického oceánu, odkud pochází čerstvý tuňák.',
        },
        {
          title: 'lutyšské vafle',
          photo: 'dish-waffle',
          text: 'Naše vždy čerstvě upečené lutyšské vafle z kynutého těsta jsou zákusek, na kterém může vzniknout závislost. Trvalo několik týdnů, než jsme jejich křupavost i chuť dovedli k dokonalosti — trpělivost se ale vyplatila.',
        },
        {
          title: 'pivo',
          photo: 'beer-pour',
          text: 'Nabízíme přes šedesát druhů belgických lahvových piv, osm svrchně kvašených piv na čepu a každých čtrnáct dní jedno pivo z tuzemského minipivovaru. Pro dámy nejraději točíme Hoegaarden Rosée a jsme hrdí na to, že nejprodávanějším lahvovým pivem je ambrové Kwak.',
        },
      ],
    },
    team: {
      eyebrow: 'Lidé',
      title: 'kdo se o vás postará',
      people: [
        { name: 'Robert Vaverka', role: 'generální manažer a spolumajitel', photo: 'team-robert-vaverka' },
        { name: 'Oldřich Matoušek', role: 'šéfkuchař', photo: 'team-oldrich-matousek' },
        { name: 'Daniela Hirschová', role: 'šéfcukrářka', photo: 'team-daniela-hirschova' },
        { name: 'Bernard Praum', role: 'manažer restaurace', photo: 'team-bernard-praum' },
      ],
    },
    events: {
      title: 'gastronomické akce',
      text: 'V průběhu roku připravujeme několik gastronomických akcí — od Krevetového festivalu a Humřích hodů až po Vánoční šneky.',
    },
    together: {
      title: 'nejsme v tom sami',
      text: 'Vaříme společně, v síti restaurací Together. Naší sesterskou restaurací je Vinohradský parlament, s kartou Together sbíráte výhody v celé síti.',
      card: 'Karta Together',
      network: 'Restaurace Together',
      parlament: 'Vinohradský parlament',
    },
  },

  gallery: {
    eyebrow: 'Galerie',
    title: 'podívejte se k nám',
    lead: 'Secesní sál s galerií, bar s vysokým sezením, kuchyně a lidé, kteří ji vedou.',
    filters: { all: 'Vše', kitchen: 'Kuchyně', interior: 'Interiér', people: 'Lidé', beer: 'Pivo', kids: 'Děti' },
    videos: {
      title: 'video',
      lead: 'Jak se jedí krevety, jak otevřít ústřici a jak se správně čepuje belgické pivo.',
      play: 'Přehrát video',
    },
    tour: {
      title: 'virtuální prohlídka',
      text: 'Projděte si restauraci ve 360° v Google Street View.',
      cta: 'Spustit prohlídku',
    },
    close: 'Zavřít',
    prev: 'Předchozí',
    next: 'Další',
    of: 'z',
  },

  photoCaptions: {
    'dish-lamb-boudin': 'Pečené jehněčí kolínko, grilovaná belgická klobása boudin blanc, omáčka z divokého česneku',
    'dish-calamari': 'Kalamáry',
    'dish-mussels': 'Mušle',
    'dish-duck': 'Grilované kachní prso, konfit ze stehna, květákové pyré a zelený chřest',
    'dish-tuna': 'Žlutoploutvý tuňák, mandlové gazpacho, fialový květák a vinaigrette s lanýžovým olejem',
    'dish-scallops': 'Restované mušle svatého Jakuba, bílá quinoa, černá čočka beluga a humrová koncentrace',
    'dish-prawns': 'Krevety Vannamei s česnekem a máslem, beurre blanc s tonka fazolí',
    'dish-octopus': 'Grilovaná chobotnice, opečené brambory s chorizem, koriandr a zázvorový vinaigrette',
    'dish-gnocchi': 'Bramborové noky s velouté z pečené dýně, ricotta a pražené vlašské ořechy',
    'dish-waffle': 'Vafle Royal',
    'dish-monkfish': 'Pečený mořský ďas v másle, grilovaný chřest a jarní omáčka ze smržů',
    'dish-asparagus-carpaccio': 'Carpaccio z bílého chřestu, limetkový vinaigrette a tartaletka s taleggiem',
    'dish-asparagus-polenta': 'Zelený chřest, lanýžová polenta a pošírované křepelčí vejce',
    'dish-escargots': 'Šneci zapečení s česnekovo-bylinkovým máslem',
    'interior-front': 'Přední část restaurace Bruxx',
    'interior-bar': 'Barová část s vysokým barovým sezením',
    'interior-middle': 'Střední část s výhledem na bar a galerii',
    'interior-stairs': 'Schody na galerii a zadní část restaurace',
    'interior-gallery': 'Galerie s místy až pro 45 hostů',
    'team-robert-vaverka': 'Robert Vaverka, generální manažer a spolumajitel',
    'team-oldrich-matousek': 'Oldřich Matoušek, šéfkuchař',
    'team-daniela-hirschova': 'Daniela Hirschová, šéfcukrářka',
    'team-bernard-praum': 'Bernard Praum, manažer restaurace',
    'beer-robert': 'Robert Vaverka',
    'beer-pour': 'Čepování belgického piva',
    'beer-orval': 'Orval',
    'beer-st-bernardus': 'St. Bernardus',
    'beer-mort-subite': 'Mort Subite',
    'kids-balls': 'Dětský koutek',
    'kids-tunnel': 'Prolézačky v dětském koutku',
    'kids-blocks': 'Kostky a hry',
    'kids-corner': 'Dětský koutek',
    'kids-table': 'Dětské menu',
  },

  videos: [
    { id: 'e4022lU2hio', title: 'Together restaurants — Společně jsme to zvládli!' },
    { id: 'qDzWX2TuUlw', title: 'Krevety Vannamei' },
    { id: 'Ur9thVuwrfc', title: 'Jak se jedí krevety' },
    { id: 'T6S6-inoGiI', title: 'Pivní sommeliér' },
    { id: '_yBkwYKqb48', title: 'Tripel Karmeliet' },
    { id: 'LkH8Cy98pQ8', title: 'Čepování piva' },
    { id: 'hmyzql3F1DU', title: 'Jak správně jíst ústřice' },
    { id: 'jLbHPebHzIo', title: 'Ústřice nejen z Francie' },
    { id: 'XKzKHAZFags', title: 'Otevírání ústřic' },
    { id: 'MDTsOQCMAl8', title: 'Jak se jedí langustýnky' },
    { id: 'sgZMQYNZ1jM', title: 'Festival ústřic' },
  ],

  kids: {
    eyebrow: 'Pro děti',
    title: 'děti se u nás cítí skvěle',
    lead: 'Společně s restaurací Vinohradský parlament máme pro děti speciální menu, tematické omalovánky a dětský koutek.',
    schedule: {
      title: 'víkend s dětmi',
      items: [
        { time: '11:30', title: 'Dětský koutek', text: 'O víkendech se otevírá už v 11:30 a hosteska v něm připravuje výtvarný program.' },
        { time: '12–16', title: 'Brunch „sněz, co můžeš“', text: 'Víkendový brunch pro děti s křupavými belgickými vaflemi.' },
        { time: '14–15', title: 'Vaříme mušle', text: 'Děti si s naším kuchařem připraví vlastní porci mušlí.' },
      ],
    },
    note: 'Ve všední dny je dětský koutek k dispozici od 11:30.',
    cta: 'Rezervovat stůl pro rodinu',
  },

  recipes: {
    eyebrow: 'Recepty Oldy Matouška',
    title: 'bruxx doma',
    lead: 'Dlouho jste v Bruxxu nebyli? Vyzkoušejte doma některé z našich jednoduchých jídel. Mezi třemi recepty, které šéfkuchař Oldřich Matoušek odtajnil, je i legendární stálice lístku — cibulačka. Přejeme dobrou chuť.',
    servings: 'Porce',
    time: 'Příprava',
    minutes: '{n} min',
    ingredients: 'Ingredience',
    steps: 'Postup',
    less: 'Méně porcí',
    more: 'Více porcí',
    pinch: 'špetka',
    print: 'Vytisknout',
    list: [
      {
        id: 'zampiony',
        title: 'Nakládané žampiony',
        photo: 'recipe-mushrooms',
        serves: 4,
        minutes: 30,
        groups: [
          {
            title: '',
            items: [
              { qty: 500, unit: 'g', name: 'žampionů' },
              { qty: 200, unit: 'g', name: 'cukru' },
              { qty: 40, unit: 'ml', name: 'bílého vinného octa' },
              { qty: 100, unit: 'ml', name: 'vody' },
              { name: 'mletý anýz' },
              { name: 'koriandrová semínka' },
              { name: 'čerstvé chilli' },
              { name: 'špetka soli' },
            ],
          },
        ],
        steps: [
          'Do hrnce nalijte vodu, přidejte cukr, vinný ocet, anýz, koriandrová semínka, sůl a chilli. Přiveďte k varu.',
          'Nechte krátce svařit, aby se chutě propojily.',
          'Přidejte žampiony a vařte přibližně 4 minuty.',
          'Směs přelijte do nádoby a nechte vychladnout.',
          'Nádobu uzavřete a uchovávejte v chladu.',
        ],
      },
      {
        id: 'cibulacka',
        title: 'Cibulačka Bruxx',
        photo: 'recipe-onion-soup',
        serves: 4,
        minutes: 60,
        groups: [
          {
            title: '',
            items: [
              { qty: 50, unit: 'g', name: 'cibule' },
              { qty: 50, unit: 'g', name: 'oleje' },
              { qty: 1.2, unit: 'l', name: 'kuřecího vývaru' },
              { qty: 50, unit: 'ml', name: 'worcesterské omáčky' },
              { qty: 50, unit: 'g', name: 'cukru' },
              { qty: 20, unit: 'g', name: 'česneku' },
              { qty: 100, unit: 'ml', name: 'sherry' },
              { qty: 4, unit: '', name: 'plátky bílého chleba' },
              { qty: 50, unit: 'g', name: 'cheddaru' },
              { name: 'čerstvý tymián' },
              { name: 'špetka soli' },
            ],
          },
        ],
        steps: [
          'Cibuli oloupejte a nakrájejte na půlkolečka.',
          'Na oleji ji orestujte do světle hněda.',
          'Přidejte česnek, tymián a cukr a nechte zkaramelizovat.',
          'Zalijte kuřecím vývarem, osolte a přidejte worcesterskou omáčku.',
          'Vařte přibližně 30 minut. Na závěr přidejte sherry.',
          'Chléb nakrájejte a opečte v troubě na krutony.',
          'Krutony položte na polévku, posypte sýrem a krátce zapečte dozlatova.',
        ],
      },
      {
        id: 'remulada',
        title: 'Celerová remuláda',
        photo: 'recipe-celeriac',
        serves: 4,
        minutes: 30,
        groups: [
          {
            title: 'Na remuládu',
            items: [
              { qty: 500, unit: 'g', name: 'celeru' },
              { qty: 2, unit: '', name: 'vejce' },
            ],
          },
          {
            title: 'Na majonézu',
            items: [
              { qty: 3, unit: '', name: 'žloutky' },
              { qty: 20, unit: 'g', name: 'dijonské hořčice' },
              { qty: 50, unit: 'ml', name: 'bílého vinného octa' },
              { qty: 200, unit: 'ml', name: 'olivového oleje' },
              { name: 'špetka soli' },
            ],
          },
        ],
        steps: [
          'Žloutky i olivový olej nechte mít stejnou pokojovou teplotu.',
          'V misce smíchejte žloutky s dijonskou hořčicí a trochou vinného octa.',
          'Za stálého šlehání pomalu přilévejte olivový olej, dokud nevznikne hustá majonéza.',
          'Do hotové majonézy přidejte najemno nastrouhaný celer a promíchejte.',
          'Osolte a dochuťte podle potřeby.',
          'Vejce uvařte natvrdo, nasekejte a použijte na ozdobení.',
        ],
      },
    ],
  },

  contact: {
    eyebrow: 'Kontakt',
    title: 'přijďte k nám',
    lead: 'Najdete nás přímo na náměstí Míru, pár kroků od stanice metra A.',
    address: 'Adresa',
    phone: 'Telefon',
    email: 'E-mail',
    hours: 'Otevírací doba',
    today: 'dnes',
    route: 'Naplánovat trasu',
    showMap: 'Načíst mapu',
    mapNote: 'Mapu od Googlu načteme až po kliknutí.',
    mapTitle: 'Mapa: Bruxx, Náměstí Míru 9',
    getting: {
      title: 'jak se k nám dostat',
      items: [
        { label: 'Metro', text: 'A — Náměstí Míru' },
        { label: 'Tramvaj', text: 'zastávka Náměstí Míru' },
      ],
    },
    operator: 'Provozovatel',
    company: ['Husa Catering s.r.o.', 'Říční 539/2', '118 00 Praha 1 – Malá Strana', 'IČO 24717576', 'DIČ CZ24717576'],
    social: 'Sledujte nás',
    reserveTitle: 'rezervace stolu',
    reserveText: 'Stůl si zarezervujete online během minuty. Pro větší skupiny a uzavřené společnosti nám raději zavolejte.',
  },

  reservation: {
    title: 'Rezervovat stůl v Bruxx',
    frame: 'Rezervační formulář',
    loading: 'Načítáme rezervační systém…',
    phone: 'Raději telefonicky?',
    close: 'Zavřít',
  },

  privacy: {
    eyebrow: 'GDPR',
    title: 'ochrana osobních údajů',
    note: '',
  },

  footer: {
    tagline: 'Belgická brasserie v Praze',
    explore: 'Bruxx',
    visit: 'Návštěva',
    follow: 'Sledujte nás',
    together: 'Nejsme v tom sami. Vaříme společně, v síti restaurací Together.',
    privacy: 'Ochrana osobních údajů',
    rights: 'Všechna práva vyhrazena.',
    top: 'Nahoru',
  },

  notFound: {
    title: 'a safra!',
    text: 'Tuhle stránku jsme nenašli. Možná ji spláchla vlna mušlí.',
    home: 'Zpět na úvod',
  },
}
