// English copy, following the English version of bruxx.cz.
export default {
  meta: {
    site: 'Bruxx',
    tagline: 'Belgian brasserie in Prague',
    description:
      'A Belgian brasserie on Náměstí Míru: fresh mussels three times a week, fries double-fried in beef tallow, more than 60 Belgian beers and Liège waffles.',
  },

  nav: {
    skip: 'Skip to content',
    home: 'Home',
    menu: 'Menu',
    beer: 'Beer',
    about: 'About',
    gallery: 'Gallery',
    kids: 'For kids',
    recipes: 'Recipes',
    contact: 'Contact',
    reserve: 'Book',
    reserveTable: 'Book a table',
    call: 'Call',
    open: 'Open menu',
    close: 'Close menu',
    language: 'Language',
    themeLight: 'Light theme',
    themeDark: 'Dark theme',
    main: 'Main navigation',
  },

  status: {
    openUntil: 'Open until {t}',
    opensToday: 'Opens today at {t}',
    opensOn: 'Opens {d} at {t}',
    tomorrow: 'tomorrow',
  },

  days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  daysRange: { '1': 'Monday', '2,3': 'Tuesday – Wednesday', '4,5,6': 'Thursday – Saturday', '0': 'Sunday' },

  home: {
    hero: {
      eyebrow: 'Náměstí Míru · Prague 2',
      title: ['belgian', 'brasserie', 'in prague'],
      lead: 'Fresh mussels, crispy fries, perfectly chilled beer and legendary waffles. The four cornerstones Bruxx is built on.',
      menu: 'See the menu',
      scroll: 'Scroll',
    },
    marquee: ['moules', 'frites', 'bière', 'gaufres', 'huîtres', 'escargots', 'crevettes'],
    pillars: {
      eyebrow: 'Bruxx exclusive',
      title: 'four cornerstones',
      items: [
        {
          key: 'mussels',
          title: 'fresh mussels',
          kicker: '3× a week from Yerseke',
          text: 'Three times a week we bring Dutch mussels from the Eastern Scheldt. Guests love them in white wine; our chef’s favourite is the Tin Tin.',
          photo: 'dish-mussels',
        },
        {
          key: 'fries',
          title: 'fries',
          kicker: 'double-fried in beef tallow',
          text: 'It starts with choosing the right potato and ends with the double frying typical of Belgian cuisine. Served with home-made olive-oil mayonnaise.',
        },
        {
          key: 'beer',
          title: 'beer',
          kicker: '60+ bottled · 8 on tap',
          text: 'From witbier, lambic and geuze to Trappist ales. Our best-selling bottled beer is Kwak, one of the most famous Belgian ambers.',
          photo: 'beer-pour',
        },
        {
          key: 'waffles',
          title: 'Liège waffles',
          kicker: 'from leavened dough',
          text: 'Some desserts you can get addicted to. It took us weeks to get their crispness and taste just right — it was worth it.',
          photo: 'dish-waffle',
        },
      ],
      more: 'The whole story',
    },
    lunch: {
      eyebrow: 'Lunch menu',
      title: 'today’s lunch',
      hours: 'Mon–Fri · 11:00–15:00 or until sold out',
      weekend: 'On Saturdays, Sundays and public holidays we do not prepare a daily menu — please choose from the regular menu.',
      empty: 'Today’s lunch menu is on its way.',
      full: 'Full menu',
    },
    stats: [
      { value: 60, suffix: '+', label: 'Belgian bottled beers' },
      { value: 8, suffix: '', label: 'top-fermented beers on tap' },
      { value: 3, suffix: '×', label: 'a week fresh mussels and fish' },
      { value: 45, suffix: '', label: 'seats in the gallery for private parties' },
    ],
    dishes: {
      eyebrow: 'From our kitchen',
      title: 'plates worth the trip',
      hint: 'Drag sideways',
    },
    beer: {
      eyebrow: 'Beer sommelier',
      quote: 'At Bruxx, we have always specialised in the best beers from Belgium.',
      author: 'Robert Vaverka',
      role: 'general manager and co-owner',
      cta: 'Get a beer recommendation',
    },
    private: {
      eyebrow: 'Private events',
      title: 'the gallery, just for you',
      text: 'The restaurant’s gallery seats up to 45 guests and can be reserved for a private party — a birthday, a company dinner or a Belgian beer tasting.',
      cta: 'Plan an event',
    },
    events: {
      eyebrow: 'Events & seasons',
      title: 'feasts throughout the year',
      lead: 'Seasonal specials and our chefs’ signature dishes are served all day long. Follow us — the next gourmet experience is already in the making.',
      items: [
        { title: 'Prawn Festival', photo: 'dish-prawns' },
        { title: 'Lobster Feast', photo: 'dish-scallops' },
        { title: 'Christmas Snails', photo: 'dish-escargots' },
      ],
    },
    teasers: {
      kids: { eyebrow: 'For kids', title: 'play area and weekend brunch', cta: 'For families' },
      recipes: { eyebrow: 'Recipes', title: 'Bruxx onion soup at home', cta: 'Chef’s recipes' },
    },
    visit: {
      eyebrow: 'Find us',
      title: 'náměstí míru 9',
      route: 'Get directions',
      hours: 'Opening hours',
    },
  },

  menu: {
    eyebrow: 'Food and drinks',
    title: 'menu',
    lead: 'Belgian recipes, mussels fresh three times a week and a home-made baguette with every dish, on the house.',
    tabs: { lunch: 'Lunch', food: 'Food', drinks: 'Drinks', wine: 'Wine', beer: 'Beer' },
    search: 'Search the menu',
    searchPlaceholder: 'Mussels, Kwak, waffle…',
    allergens: 'Allergens',
    exclude: 'Hide dishes containing',
    clear: 'Clear filter',
    none: 'Nothing found. Try another word or clear the filter.',
    live: 'Live from the kitchen',
    snapshot: 'Menu as of {d}',
    currency: 'CZK',
    jump: 'Categories',
    allergensTitle: 'Allergens',
    allergensNote: 'Numbers next to dishes mark allergens. Our staff will be happy to help.',
    lunchTitle: 'Lunch menu',
    lunchHours: 'Monday to Friday, 11:00–15:00 or until sold out',
    new: 'new',
    items: '{n} items',
    langNote: '',
  },

  allergens: {
    1: 'cereals containing gluten',
    2: 'crustaceans',
    3: 'eggs',
    4: 'fish',
    5: 'peanuts',
    6: 'soy',
    7: 'milk',
    8: 'tree nuts',
    9: 'celery',
    10: 'mustard',
    11: 'sesame',
    12: 'sulphites',
    13: 'lupin',
    14: 'molluscs',
  },

  subscribe: {
    title: 'Lunch menu by e-mail',
    text: 'Every weekday morning we will send you what is cooking today.',
    label: 'Your e-mail',
    placeholder: 'name@email.com',
    submit: 'Subscribe',
    consent: 'I agree to the processing of personal data',
    sent: 'Done — your e-mail has been sent for subscription.',
    added: 'Your e-mail has been added.',
    removed: 'Your e-mail has been unsubscribed.',
    invalid: 'That e-mail address does not look right.',
    unavailable: 'Subscription cannot be sent right now. Please try again in a moment.',
  },

  beer: {
    eyebrow: 'Belgian beer',
    title: 'beer',
    lead: 'At Bruxx, we have always specialised in the best beers from Belgium. Let our general manager, Robert Vaverka, recommend them himself.',
    intro: {
      name: 'Robert Vaverka',
      role: 'general manager, co-owner and beer sommelier',
      text: 'Our beer sommeliers will guide you through the world of Belgian beer, from witbier, lambic and geuze to Trappist ales. We have eight top-fermented beers on tap and, every two weeks, a new one from a Czech microbrewery.',
    },
    sections: [
      {
        title: 'Fruit beers',
        photo: 'beer-st-bernardus',
        paragraphs: [
          'My favourite fruit beer is Kasteel Rouge, made from Kasteel Donker dark beer. It is aged and fermented on sour cherries for over six months and, at 8%, it is one of Belgium’s strongest fruit beers.',
          'A few years ago I visited the Van Honsebrouck brewery, where it is made, and sat down over a few good beers with the owner, Xavier Van Honsebrouck. His family owns a château, which is pictured on the foot of the glass.',
          'We like to pair it with venison, dishes with richer sauces and desserts with wild berries. Another one I recommend is Liefmans Fruitesse on the Rocks — served in a glass full of ice, it also makes a fine aperitif.',
        ],
      },
      {
        title: 'Semi-dark beers',
        photo: 'beer-pour',
        paragraphs: [
          'Kwak from the Bosteels brewery is served in a unique hourglass-shaped glass, and pouring it creates an avalanche effect. At 8.4%, this semi-dark beer is a real heavyweight.',
          'It is best enjoyed with slow-braised beef brisket à la mode with root vegetables, herbs and parsley potatoes.',
        ],
      },
      {
        title: 'Light beers',
        photo: 'beer-orval',
        paragraphs: [
          'Another heavyweight at 8.3% is Hopus from Brasserie Lefebvre. We recommend it with the vegetarian ravioli with pecans and mascarpone — and the serving will impress you: the sediment from the bottle comes in a small shot glass, so you set the bitterness yourself.',
          'My favourite light beer at Bruxx is Brugge Tripel from De Gouden Boom. Bright golden, with a pleasant bitterness and citrus notes at the finish. I would pair it with grilled calamari, prawns and mussels in saffron fumet.',
        ],
      },
      {
        title: 'IPA',
        paragraphs: [
          'IPA — a hoppier style with more alcohol — is on our list too. When India was still a British colony, more hops and alcohol were added so the beer would survive the long voyage.',
        ],
      },
      {
        title: 'Lambic beers',
        photo: 'beer-mort-subite',
        paragraphs: [
          'I can’t leave out Boon Geuze at 7%. It is a lambic made by spontaneous fermentation; geuze means a blend of old and young lambics. When I first tasted it in Antwerp, I thought it had gone off — today it is one of my favourite styles, and I recommend it especially with oysters.',
        ],
      },
      {
        title: 'A beer for the ladies',
        paragraphs: [
          'For the ladies I recommend Mongozo Coconut from the Huyghe brewery, at 3.6%. It is served in a coconut shell and tastes like a low-alcohol piña colada — perfect with a light dessert such as our pistachio crème brûlée.',
        ],
      },
    ],
    explorer: {
      eyebrow: 'Beer list',
      title: 'find your beer',
      lead: 'Our whole current beer list. Filter by style and strength.',
      all: 'All',
      strength: 'Strength',
      strengths: { all: 'Any', light: 'up to 5%', mid: '5–8%', strong: 'over 8%' },
      sort: 'Sort',
      sorts: { menu: 'As listed', abv: 'By strength', price: 'By price' },
      count: '{n} beers',
      none: 'We don’t have a beer like that on the list right now.',
    },
  },

  about: {
    eyebrow: 'About us',
    title: 'a brasserie of belgian recipes',
    lead: 'Fresh mussels, crispy fries, perfectly chilled beer and legendary waffles. These are the four cornerstones of Bruxx, the Belgian brasserie we have built in the heart of Prague.',
    story: [
      'Led by head chef Oldřich Matoušek and co-owners Jan Pípal and Robert Vaverka, we prepare our menu using authentic Belgian recipes and have fresh farm-raised mussels delivered to Prague three times a week.',
      'Like the Belgians, we take our fries seriously and make them ourselves. Our menu also features Liège specialities, fresh fish, oysters, snails and other authentic ingredients, along with Belgian pralines.',
      'From Monday to Friday we serve our lunch menu from 11 a.m. to 3 p.m., or until sold out. Our children’s play area opens at 11:30 a.m., with supervision at weekends.',
    ],
    exclusive: {
      eyebrow: 'Bruxx exclusive',
      title: 'what we care about',
      items: [
        {
          title: 'fresh mussels',
          photo: 'dish-mussels',
          text: 'Three times a week we import Dutch mussels to Prague from the Eastern Scheldt, near the town of Yerseke. Apart from our original recipes, it matters to us that the mussels on your table are always fresh and of excellent quality. Guests prefer them in white wine; chef Olda Matoušek loves the Tin Tin.',
        },
        {
          title: 'fries',
          text: 'Hardly anybody can imagine how much work goes into crispy, golden fries. It all starts with choosing the right variety and type of potato and finishes with the double frying in beef tallow so typical of Belgian cuisine.',
        },
        {
          title: 'fish',
          photo: 'dish-tuna',
          text: 'Like the mussels, fresh fish arrives three times a week — from the Mediterranean, from the west and north coasts of Europe, and from the Indian Ocean, where our fresh tuna comes from.',
        },
        {
          title: 'Liège waffles',
          photo: 'dish-waffle',
          text: 'Our Liège waffles, always freshly baked from leavened dough, are a dessert you can get addicted to. It took several weeks to perfect their crispness and taste — the patience paid off.',
        },
        {
          title: 'beer',
          photo: 'beer-pour',
          text: 'More than sixty Belgian bottled beers, eight top-fermented beers on tap and, every two weeks, a beer from a Czech microbrewery. For the ladies we like to pour Hoegaarden Rosée, and we are proud that our best-selling bottled beer is Kwak.',
        },
      ],
    },
    team: {
      eyebrow: 'People',
      title: 'who looks after you',
      people: [
        { name: 'Robert Vaverka', role: 'general manager and co-owner', photo: 'team-robert-vaverka' },
        { name: 'Oldřich Matoušek', role: 'head chef', photo: 'team-oldrich-matousek' },
        { name: 'Daniela Hirschová', role: 'head pastry chef', photo: 'team-daniela-hirschova' },
        { name: 'Bernard Praum', role: 'restaurant manager', photo: 'team-bernard-praum' },
      ],
    },
    events: {
      title: 'culinary events',
      text: 'Throughout the year we host several culinary events, from the Prawn Festival and Lobster Feast to Christmas Snails.',
    },
    together: {
      title: 'we are not alone',
      text: 'We cook together, in the Together restaurant network. Our sister restaurant is Vinohradský parlament, and the Together card brings benefits across the whole network.',
      card: 'Together card',
      network: 'Together restaurants',
      parlament: 'Vinohradský parlament',
    },
  },

  gallery: {
    eyebrow: 'Gallery',
    title: 'come and have a look',
    lead: 'An Art Nouveau hall with a gallery, a bar with high seating, the kitchen and the people who run it.',
    filters: { all: 'All', kitchen: 'Kitchen', interior: 'Interior', people: 'People', beer: 'Beer', kids: 'Kids' },
    videos: {
      title: 'video',
      lead: 'How to eat prawns, how to open an oyster and how a Belgian beer is poured.',
      play: 'Play video',
    },
    tour: {
      title: 'virtual tour',
      text: 'Walk through the restaurant in 360° on Google Street View.',
      cta: 'Start the tour',
    },
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    of: 'of',
  },

  photoCaptions: {
    'dish-lamb-boudin': 'Roast lamb shank, grilled Belgian boudin blanc, wild garlic sauce',
    'dish-calamari': 'Calamari',
    'dish-mussels': 'Mussels',
    'dish-duck': 'Grilled duck breast, leg confit, cauliflower purée and green asparagus',
    'dish-tuna': 'Yellowfin tuna, almond gazpacho, purple cauliflower and truffle-oil vinaigrette',
    'dish-scallops': 'Seared scallops, white quinoa, black beluga lentils and lobster reduction',
    'dish-prawns': 'Vannamei prawns with garlic and butter, tonka bean beurre blanc',
    'dish-octopus': 'Grilled octopus, roast potatoes with chorizo, coriander and ginger vinaigrette',
    'dish-gnocchi': 'Potato gnocchi with roast pumpkin velouté, ricotta and toasted walnuts',
    'dish-waffle': 'Waffle Royal',
    'dish-monkfish': 'Butter-roasted monkfish, grilled asparagus and spring morel sauce',
    'dish-asparagus-carpaccio': 'White asparagus carpaccio, lime vinaigrette and taleggio tartlet',
    'dish-asparagus-polenta': 'Green asparagus, truffle polenta and poached quail egg',
    'dish-escargots': 'Snails baked with garlic and herb butter',
    'interior-front': 'The front of the restaurant',
    'interior-bar': 'The bar with high seating',
    'interior-middle': 'The middle room, looking towards the bar and gallery',
    'interior-stairs': 'Stairs to the gallery and the back room',
    'interior-gallery': 'The gallery, seating up to 45 guests',
    'team-robert-vaverka': 'Robert Vaverka, general manager and co-owner',
    'team-oldrich-matousek': 'Oldřich Matoušek, head chef',
    'team-daniela-hirschova': 'Daniela Hirschová, head pastry chef',
    'team-bernard-praum': 'Bernard Praum, restaurant manager',
    'beer-robert': 'Robert Vaverka',
    'beer-pour': 'Pouring a Belgian beer',
    'beer-orval': 'Orval',
    'beer-st-bernardus': 'St. Bernardus',
    'beer-mort-subite': 'Mort Subite',
    'kids-balls': 'The play area',
    'kids-tunnel': 'Climbing tunnel in the play area',
    'kids-blocks': 'Blocks and games',
    'kids-corner': 'The play area',
    'kids-table': 'Kids’ menu',
  },

  videos: [
    { id: 'e4022lU2hio', title: 'Together restaurants — we made it together!' },
    { id: 'qDzWX2TuUlw', title: 'Vannamei prawns' },
    { id: 'Ur9thVuwrfc', title: 'How to eat prawns' },
    { id: 'T6S6-inoGiI', title: 'The beer sommelier' },
    { id: '_yBkwYKqb48', title: 'Tripel Karmeliet' },
    { id: 'LkH8Cy98pQ8', title: 'Pouring beer' },
    { id: 'hmyzql3F1DU', title: 'How to eat oysters' },
    { id: 'jLbHPebHzIo', title: 'Oysters, not only from France' },
    { id: 'XKzKHAZFags', title: 'Opening oysters' },
    { id: 'MDTsOQCMAl8', title: 'How to eat langoustines' },
    { id: 'sgZMQYNZ1jM', title: 'Oyster festival' },
  ],

  kids: {
    eyebrow: 'For kids',
    title: 'kids have a great time here',
    lead: 'Together with the Vinohradský parlament restaurant, we offer children a special menu, themed colouring books and a play area.',
    schedule: {
      title: 'weekends with kids',
      items: [
        { time: '11:30', title: 'Play area', text: 'At weekends it opens as early as 11:30, and our hostess runs an arts and crafts programme.' },
        { time: '12–16', title: '“All you can eat” brunch', text: 'A weekend brunch for children with crispy Belgian waffles.' },
        { time: '14–15', title: 'Cooking mussels', text: 'Kids cook their own portion of mussels with our chef.' },
      ],
    },
    note: 'On weekdays the play area is open from 11:30.',
    cta: 'Book a family table',
  },

  recipes: {
    eyebrow: 'Recipes by Olda Matoušek',
    title: 'bruxx at home',
    lead: 'Haven’t been to Bruxx for a while? Try some of our simple dishes at home. Among the three recipes chef Oldřich Matoušek has revealed is a legend of our menu — the onion soup. Enjoy.',
    servings: 'Servings',
    time: 'Time',
    minutes: '{n} min',
    ingredients: 'Ingredients',
    steps: 'Method',
    less: 'Fewer servings',
    more: 'More servings',
    pinch: 'pinch',
    print: 'Print',
    list: [
      {
        id: 'zampiony',
        title: 'Pickled mushrooms',
        photo: 'recipe-mushrooms',
        serves: 4,
        minutes: 30,
        groups: [
          {
            title: '',
            items: [
              { qty: 500, unit: 'g', name: 'button mushrooms' },
              { qty: 200, unit: 'g', name: 'sugar' },
              { qty: 40, unit: 'ml', name: 'white wine vinegar' },
              { qty: 100, unit: 'ml', name: 'water' },
              { name: 'ground anise' },
              { name: 'coriander seeds' },
              { name: 'fresh chilli' },
              { name: 'a pinch of salt' },
            ],
          },
        ],
        steps: [
          'Pour the water into a pot and add the sugar, vinegar, anise, coriander seeds, salt and chilli. Bring to the boil.',
          'Let it simmer briefly so the flavours come together.',
          'Add the mushrooms and cook for about 4 minutes.',
          'Pour into a container and leave to cool.',
          'Close the container and keep it in a cool place.',
        ],
      },
      {
        id: 'cibulacka',
        title: 'Bruxx onion soup',
        photo: 'recipe-onion-soup',
        serves: 4,
        minutes: 60,
        groups: [
          {
            title: '',
            items: [
              { qty: 50, unit: 'g', name: 'onion' },
              { qty: 50, unit: 'g', name: 'oil' },
              { qty: 1.2, unit: 'l', name: 'chicken stock' },
              { qty: 50, unit: 'ml', name: 'Worcestershire sauce' },
              { qty: 50, unit: 'g', name: 'sugar' },
              { qty: 20, unit: 'g', name: 'garlic' },
              { qty: 100, unit: 'ml', name: 'sherry' },
              { qty: 4, unit: '', name: 'slices of white bread' },
              { qty: 50, unit: 'g', name: 'cheddar' },
              { name: 'fresh thyme' },
              { name: 'a pinch of salt' },
            ],
          },
        ],
        steps: [
          'Peel the onion and slice it into half-rings.',
          'Fry it in the oil until light brown.',
          'Add the garlic, thyme and sugar and let it caramelise.',
          'Pour in the chicken stock, salt it and add the Worcestershire sauce.',
          'Simmer for about 30 minutes. Finish with the sherry.',
          'Cut the bread and toast it in the oven into croutons.',
          'Lay the croutons on the soup, sprinkle with cheese and briefly grill until golden.',
        ],
      },
      {
        id: 'remulada',
        title: 'Celeriac rémoulade',
        photo: 'recipe-celeriac',
        serves: 4,
        minutes: 30,
        groups: [
          {
            title: 'For the rémoulade',
            items: [
              { qty: 500, unit: 'g', name: 'celeriac' },
              { qty: 2, unit: '', name: 'eggs' },
            ],
          },
          {
            title: 'For the mayonnaise',
            items: [
              { qty: 3, unit: '', name: 'egg yolks' },
              { qty: 20, unit: 'g', name: 'Dijon mustard' },
              { qty: 50, unit: 'ml', name: 'white wine vinegar' },
              { qty: 200, unit: 'ml', name: 'olive oil' },
              { name: 'a pinch of salt' },
            ],
          },
        ],
        steps: [
          'Let the egg yolks and olive oil come to the same room temperature.',
          'In a bowl, mix the yolks with the Dijon mustard and a little vinegar.',
          'Whisking constantly, slowly pour in the olive oil until you have a thick mayonnaise.',
          'Stir the finely grated celeriac into the mayonnaise.',
          'Season with salt to taste.',
          'Hard-boil the eggs, chop them and use them to garnish.',
        ],
      },
    ],
  },

  contact: {
    eyebrow: 'Contact',
    title: 'come and see us',
    lead: 'You’ll find us right on Náměstí Míru, a few steps from the metro line A station.',
    address: 'Address',
    phone: 'Phone',
    email: 'E-mail',
    hours: 'Opening hours',
    today: 'today',
    route: 'Get directions',
    showMap: 'Load the map',
    mapNote: 'The Google map loads only after you click.',
    mapTitle: 'Map: Bruxx, Náměstí Míru 9',
    getting: {
      title: 'getting here',
      items: [
        { label: 'Metro', text: 'A — Náměstí Míru' },
        { label: 'Tram', text: 'stop Náměstí Míru' },
      ],
    },
    operator: 'Operator',
    company: ['Husa Catering s.r.o.', 'Říční 539/2', '118 00 Praha 1 – Malá Strana', 'Company ID 24717576', 'VAT CZ24717576'],
    social: 'Follow us',
    reserveTitle: 'book a table',
    reserveText: 'Book a table online in a minute. For larger groups and private parties, please give us a call.',
  },

  reservation: {
    title: 'Book a table at Bruxx',
    frame: 'Reservation form',
    loading: 'Loading the booking system…',
    phone: 'Prefer to call?',
    close: 'Close',
  },

  privacy: {
    eyebrow: 'GDPR',
    title: 'privacy policy',
    note: '',
  },

  footer: {
    tagline: 'Belgian brasserie in Prague',
    explore: 'Bruxx',
    visit: 'Visit',
    follow: 'Follow us',
    together: 'We are not alone. We cook together, in the Together restaurant network.',
    privacy: 'Privacy policy',
    rights: 'All rights reserved.',
    top: 'Back to top',
  },

  notFound: {
    title: 'oh dear!',
    text: 'We couldn’t find this page. Perhaps a wave of mussels washed it away.',
    home: 'Back to the homepage',
  },
}
